------------------------------------------------------------------------------
-- Ejercicio 2
-- Se quiere diseñar una base de datos relacional para gestionar los datos de 
-- los socios de un club náutico. De cada socio se guardan los datos personales 
-- y los datos del barco o barcos que posee: número de matrícula, nombre, 
-- número del amarre y cuota que paga por el mismo. Además, se quiere mantener 
-- información sobre las salidas realizadas por cada barco, como la fecha y hora
-- de salida, el destino y los datos personales del patrón, que no tiene porque 
-- ser el propietario del barco, ni es necesario que sea socio del club.

--CREAR TABLA SOCIOS

CREATE TABLE SOCIOS(
ID_SOCIO NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2 (10),
APELLIDOS NVARCHAR2 (20),
DIRECCION NVARCHAR2 (30),
TELEFONO NUMBER (10)
);

--CREAR TABLA BARCOS

CREATE TABLE BARCOS(
NO_MATRICULA NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2 (15),
NO_AMARRE NUMBER,
CUOTA NUMBER,
ID_SOCIO NUMBER,
CONSTRAINT FK_ID_SOCIO FOREIGN KEY (ID_SOCIO) REFERENCES SOCIOS (ID_SOCIO)
);

--CREAR TABLA PATRON

CREATE TABLE PATRON(
ID_PATRON NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2 (10),
APELLIDOS NVARCHAR2 (20),
DIRECCION NVARCHAR2 (30),
TELEFONO NUMBER (10)
);

--CREAR TABLA SALIDAS

CREATE TABLE SALIDAS(
ID_SALIDA NUMBER PRIMARY KEY,
FECHA_HORA_SALIDA DATE,
DESTINO NVARCHAR2 (15),
NO_MATRICULA NUMBER,
ID_PATRON NUMBER,
CONSTRAINT FK_NO_MATRICULA FOREIGN KEY (NO_MATRICULA) REFERENCES BARCOS (NO_MATRICULA),
CONSTRAINT FK_ID_PATRON FOREIGN KEY (ID_PATRON) REFERENCES PATRON (ID_PATRON)
);

--CREAR SECUENCIA PARA SOCIOS
CREATE SEQUENCE SOCIOS_SEQ;

--CREAR SECUENCIA PARA PATRON
CREATE SEQUENCE PATRON_SEQ;

--CREAR SECUENCIA PARA SALIDAS
CREATE SEQUENCE SALIDAS_SEQ;

-- CREACION DE TRIGGERS PARA SECUENCIAS

CREATE TRIGGER INSERT_SOCIOS
BEFORE INSERT ON SOCIOS FOR EACH ROW BEGIN
SELECT SOCIOS_SEQ.NEXTVAL INTO:NEW.ID_SOCIO FROM DUAL;
END;

CREATE TRIGGER INSERT_PATRON
BEFORE INSERT ON PATRON FOR EACH ROW BEGIN
SELECT PATRON_SEQ.NEXTVAL INTO:NEW.ID_PATRON FROM DUAL;
END;

CREATE TRIGGER INSERT_SALIDAS
BEFORE INSERT ON SALIDAS FOR EACH ROW BEGIN
SELECT SALIDAS_SEQ.NEXTVAL INTO:NEW.ID_SALIDA FROM DUAL;
END;

-- INSERTAR 5 REGISTROS EN TABLAS
INSERT ALL
INTO SOCIOS(NOMBRE, APELLIDOS, DIRECCION, TELEFONO) VALUES ('EMMANUEL','SANDOVAL','SAN FRANCISCO MAZAPA', 5630345103)
INTO SOCIOS(NOMBRE, APELLIDOS, DIRECCION, TELEFONO) VALUES ('ALEJANDRO','CARDENAS','TECAMAC', 5517967512)
INTO SOCIOS(NOMBRE, APELLIDOS, DIRECCION, TELEFONO) VALUES ('LUIS','SC','SAN FRANCISCO MAZAPA', 5516502413)
INTO SOCIOS(NOMBRE, APELLIDOS, DIRECCION, TELEFONO) VALUES ('NANCY','AGUILAR','SANTA MARIA COATLAN', 5540114402)
INTO SOCIOS(NOMBRE, APELLIDOS, DIRECCION, TELEFONO) VALUES ('JESE','SA','SAN FRANCISCO MAZAPA', 5530345107)
SELECT * FROM DUAL;

INSERT ALL
INTO BARCOS(NO_MATRICULA, NOMBRE, NO_AMARRE, CUOTA, ID_SOCIO) VALUES (1,'BARCO 1',1, 1500, 1)
INTO BARCOS(NO_MATRICULA, NOMBRE, NO_AMARRE, CUOTA, ID_SOCIO) VALUES (2,'BARCO 2',2, 1000, 2)
INTO BARCOS(NO_MATRICULA, NOMBRE, NO_AMARRE, CUOTA, ID_SOCIO) VALUES (3,'BARCO 3',2, 1300, 3)
INTO BARCOS(NO_MATRICULA, NOMBRE, NO_AMARRE, CUOTA, ID_SOCIO) VALUES (4,'BARCO 4',1, 1500, 4)
INTO BARCOS(NO_MATRICULA, NOMBRE, NO_AMARRE, CUOTA, ID_SOCIO) VALUES (5,'BARCO 5',1, 2000, 5)
SELECT * FROM DUAL;

INSERT ALL
INTO PATRON(NOMBRE, APELLIDOS, DIRECCION, TELEFONO) VALUES ('ALEJANDRO','SG','CDMX', 5555555555)
INTO PATRON(NOMBRE, APELLIDOS, DIRECCION, TELEFONO) VALUES ('ARMANDO','AR','GDL', 6666666666)
INTO PATRON(NOMBRE, APELLIDOS, DIRECCION, TELEFONO) VALUES ('DANIEL','PG','CDMX', 7777777777)
INTO PATRON(NOMBRE, APELLIDOS, DIRECCION, TELEFONO) VALUES ('EFRAIN','AG','PUEBLA', 3333333333)
INTO PATRON(NOMBRE, APELLIDOS, DIRECCION, TELEFONO) VALUES ('ADRIANA','CG','PUEBLA', 2222222222)
SELECT * FROM DUAL;

  
INSERT ALL
INTO SALIDAS(FECHA_HORA_SALIDA, DESTINO, NO_MATRICULA, ID_PATRON) VALUES (TO_DATE('20/01/2023 06:00:10','DD-MM-YYYY HH24_MI:SS'),'ACAPULCO', 1, 2)
INTO SALIDAS(FECHA_HORA_SALIDA, DESTINO, NO_MATRICULA, ID_PATRON) VALUES (TO_DATE('10/01/2023 12:24:10','DD-MM-YYYY HH24_MI:SS'),'HUATULCO', 2, 1)
INTO SALIDAS(FECHA_HORA_SALIDA, DESTINO, NO_MATRICULA, ID_PATRON) VALUES (TO_DATE('01/01/2023 09:45:10','DD-MM-YYYY HH24_MI:SS'),'CANCUN', 3, 2)
INTO SALIDAS(FECHA_HORA_SALIDA, DESTINO, NO_MATRICULA, ID_PATRON) VALUES (TO_DATE('14/01/2023 15:00:00','DD-MM-YYYY HH24_MI:SS'),'VERACRUZ', 4, 3)
INTO SALIDAS(FECHA_HORA_SALIDA, DESTINO, NO_MATRICULA, ID_PATRON) VALUES (TO_DATE('07/01/2023 05:00:50','DD-MM-YYYY HH24_MI:SS'),'PUERTO VALLARTA', 5, 4)
SELECT * FROM DUAL;

SELECT * FROM SALIDAS;

--CONSULTAR HORARIO Y FECHA
SELECT ID_SALIDA, DESTINO, TO_CHAR(FECHA_HORA_SALIDA, 'DD/MM/YYYY HH24:MI:SS') FROM SALIDAS;

--CONSULTAR UNICAMENTE HORARIO
SELECT ID_SALIDA, DESTINO, TO_CHAR(FECHA_HORA_SALIDA, 'HH24:MI:SS') FROM SALIDAS;

COMMIT;